using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Jellyfin.Plugin.Streamyfin.Configuration.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Jellyfin.Plugin.Streamyfin.Db;

/// <summary>
/// The plugin's persistence, over EF Core.
/// </summary>
/// <remarks>
/// A context is created per operation rather than held. Contexts are cheap, and
/// a short lived one keeps the change tracker from growing and removes the need
/// for the reader writer lock the hand written store carried.
/// </remarks>
public class PluginDatabase
{
    /// <summary>
    /// The database written by the hand written SQLite store this replaces.
    /// It is read once and then left alone, so downgrading still finds its data.
    /// </summary>
    internal const string LegacyFileName = "streamyfin_plugin.db";

    private const string FileName = "streamyfin.db";

    private readonly ILogger<PluginDatabase>? _logger;

    /// <summary>
    /// Initializes a new instance of the <see cref="PluginDatabase"/> class, applying
    /// migrations and running any pending one time import.
    /// </summary>
    /// <param name="path">Directory the database lives in.</param>
    /// <param name="logger">Optional logger.</param>
    public PluginDatabase(string path, ILogger<PluginDatabase>? logger = null)
    {
        ArgumentNullException.ThrowIfNull(path);

        _logger = logger;
        Directory.CreateDirectory(path);
        DbFilePath = Path.Combine(path, FileName);
        LegacyDbFilePath = Path.Combine(path, LegacyFileName);

        using var context = CreateContext();
        context.Database.Migrate();

        ImportLegacyDeviceTokens(context);
    }

    /// <summary>
    /// Gets the full path of the database file.
    /// </summary>
    public string DbFilePath { get; }

    /// <summary>
    /// Gets the full path of the database this one replaced.
    /// </summary>
    internal string LegacyDbFilePath { get; }

    /// <summary>
    /// Creates a context against this database.
    /// </summary>
    /// <returns>A new context the caller owns.</returns>
    public StreamyfinDbContext CreateContext() => new(DbFilePath);

    /// <summary>
    /// Gets the push tokens for every device a user is currently signed in on.
    /// </summary>
    /// <param name="userId">Jellyfin user id.</param>
    /// <returns>The user's device tokens.</returns>
    public List<DeviceToken> GetUserDeviceTokens(Guid userId)
    {
        using var context = CreateContext();
        return context.DeviceTokens.AsNoTracking()
            .Where(t => t.UserId == userId)
            .ToList();
    }

    /// <summary>
    /// Gets every known device token.
    /// </summary>
    /// <returns>All device tokens.</returns>
    public List<DeviceToken> GetAllDeviceTokens()
    {
        using var context = CreateContext();
        return context.DeviceTokens.AsNoTracking().ToList();
    }

    /// <summary>
    /// Gets the token registered for one device.
    /// </summary>
    /// <param name="deviceId">Device id generated by the app.</param>
    /// <returns>The token, or <c>null</c> when the device is unknown.</returns>
    public DeviceToken? GetDeviceTokenForDeviceId(Guid deviceId)
    {
        using var context = CreateContext();
        return context.DeviceTokens.AsNoTracking()
            .FirstOrDefault(t => t.DeviceId == deviceId);
    }

    /// <summary>
    /// Registers a token for a device, replacing whatever that device had before.
    /// </summary>
    /// <param name="token">The token to store. Its timestamp is set here.</param>
    /// <returns>The stored token, with its timestamp.</returns>
    public DeviceToken AddDeviceToken(DeviceToken token)
    {
        ArgumentNullException.ThrowIfNull(token);

        using var context = CreateContext();

        var timestamp = DateTime.UtcNow.ToFileTime();
        var existing = context.DeviceTokens.FirstOrDefault(t => t.DeviceId == token.DeviceId);

        // Updated in place rather than removed and re-added. Two SaveChanges calls
        // are two transactions, and a failure between them would leave the device
        // with no token at all, which the hand written store avoided by doing both
        // inside one transaction.
        if (existing is not null)
        {
            existing.Token = token.Token;
            existing.UserId = token.UserId;
            existing.Timestamp = timestamp;
        }
        else
        {
            token.Timestamp = timestamp;
            context.DeviceTokens.Add(token);
        }

        context.SaveChanges();

        token.Timestamp = timestamp;
        return token;
    }

    /// <summary>
    /// Counts the registered devices.
    /// </summary>
    /// <returns>How many device tokens are stored.</returns>
    public long TotalDevicesCount()
    {
        using var context = CreateContext();
        return context.DeviceTokens.LongCount();
    }

    /// <summary>
    /// Forgets a device.
    /// </summary>
    /// <param name="deviceId">Device id generated by the app.</param>
    public void RemoveDeviceToken(Guid deviceId)
    {
        using var context = CreateContext();

        var existing = context.DeviceTokens.FirstOrDefault(t => t.DeviceId == deviceId);
        if (existing is null)
        {
            return;
        }

        context.DeviceTokens.Remove(existing);
        context.SaveChanges();
    }

    /// <summary>
    /// Removes every device token.
    /// </summary>
    public void Purge()
    {
        using var context = CreateContext();
        context.DeviceTokens.RemoveRange(context.DeviceTokens);
        context.SaveChanges();
    }

    /// <summary>
    /// Reads the configuration the server declares for everyone.
    /// </summary>
    /// <returns>The stored JSON, or <c>null</c> before anything has been written.</returns>
    public string? GetGlobalConfigJson()
    {
        using var context = CreateContext();
        return context.GlobalConfigurations.AsNoTracking()
            .FirstOrDefault(c => c.Id == GlobalConfiguration.Current)?.ConfigJson;
    }

    /// <summary>
    /// Writes the configuration the server declares for everyone.
    /// </summary>
    /// <param name="configJson">The configuration, as JSON.</param>
    public void SaveGlobalConfigJson(string configJson)
    {
        using var context = CreateContext();

        var existing = context.GlobalConfigurations
            .FirstOrDefault(c => c.Id == GlobalConfiguration.Current);

        if (existing is null)
        {
            context.GlobalConfigurations.Add(new GlobalConfiguration
            {
                Id = GlobalConfiguration.Current,
                ConfigJson = configJson
            });
        }
        else
        {
            existing.ConfigJson = configJson;
        }

        context.SaveChanges();
    }

    /// <summary>
    /// Carries the configuration over from Jellyfin's plugin XML, once.
    /// </summary>
    /// <param name="configJson">The configuration as it stands in the XML, as JSON.</param>
    /// <returns>True when this call performed the import.</returns>
    /// <remarks>
    /// Same shape as the device token import: a marker written in the same transaction
    /// as the row, so a failure leaves neither and the next start retries. The XML file
    /// is never written to and never deleted, so downgrading to a build that reads it
    /// finds it exactly as it was left.
    /// </remarks>
    public bool ImportGlobalConfiguration(string configJson)
    {
        using var context = CreateContext();

        if (context.ImportMarkers.Any(m => m.Name == ImportMarker.LegacyGlobalConfig))
        {
            return false;
        }

        context.GlobalConfigurations.Add(new GlobalConfiguration
        {
            Id = GlobalConfiguration.Current,
            ConfigJson = configJson
        });

        context.ImportMarkers.Add(new ImportMarker
        {
            Name = ImportMarker.LegacyGlobalConfig,
            ImportedAt = DateTimeOffset.UtcNow,
            RowsImported = 1
        });

        context.SaveChanges();
        return true;
    }

    /// <summary>
    /// Gets every settings group.
    /// </summary>
    /// <returns>The groups, in layer order.</returns>
    public List<SettingsGroup> GetSettingsGroups()
    {
        using var context = CreateContext();
        return SettingsResolver.InLayerOrder(context.SettingsGroups.AsNoTracking().ToList()).ToList();
    }

    /// <summary>
    /// Gets one settings group.
    /// </summary>
    /// <param name="id">The group id.</param>
    /// <returns>The group, or <c>null</c> when there is no such group.</returns>
    public SettingsGroup? GetSettingsGroup(Guid id)
    {
        using var context = CreateContext();
        return context.SettingsGroups.AsNoTracking().FirstOrDefault(g => g.Id == id);
    }

    /// <summary>
    /// Creates or updates a settings group.
    /// </summary>
    /// <param name="group">The group. An empty id means create.</param>
    /// <returns>The stored group, with its id.</returns>
    public SettingsGroup SaveSettingsGroup(SettingsGroup group)
    {
        ArgumentNullException.ThrowIfNull(group);

        using var context = CreateContext();

        if (group.Id == Guid.Empty)
        {
            group.Id = Guid.NewGuid();
            context.SettingsGroups.Add(group);
        }
        else
        {
            var existing = context.SettingsGroups.FirstOrDefault(g => g.Id == group.Id);
            if (existing is null)
            {
                context.SettingsGroups.Add(group);
            }
            else
            {
                existing.Name = group.Name;
                existing.Priority = group.Priority;
                existing.SettingsJson = group.SettingsJson;
            }
        }

        context.SaveChanges();
        return group;
    }

    /// <summary>
    /// Deletes a settings group and everyone's membership of it.
    /// </summary>
    /// <param name="id">The group id.</param>
    /// <remarks>
    /// Both in one transaction. A group deleted while its memberships survive would
    /// leave rows that resolve to nothing and reappear if the id were ever reused.
    /// </remarks>
    public void RemoveSettingsGroup(Guid id)
    {
        using var context = CreateContext();

        var existing = context.SettingsGroups.FirstOrDefault(g => g.Id == id);
        if (existing is null)
        {
            return;
        }

        context.SettingsGroupMembers.RemoveRange(
            context.SettingsGroupMembers.Where(m => m.GroupId == id));
        context.SettingsGroups.Remove(existing);
        context.SaveChanges();
    }

    /// <summary>
    /// Gets the members of a group.
    /// </summary>
    /// <param name="groupId">The group id.</param>
    /// <returns>The Jellyfin user ids.</returns>
    public List<Guid> GetGroupMembers(Guid groupId)
    {
        using var context = CreateContext();
        return context.SettingsGroupMembers.AsNoTracking()
            .Where(m => m.GroupId == groupId)
            .Select(m => m.UserId)
            .ToList();
    }

    /// <summary>
    /// Replaces the membership of a group.
    /// </summary>
    /// <param name="groupId">The group id.</param>
    /// <param name="userIds">Who should be in it afterwards.</param>
    public void SetGroupMembers(Guid groupId, IEnumerable<Guid> userIds)
    {
        using var context = CreateContext();

        context.SettingsGroupMembers.RemoveRange(
            context.SettingsGroupMembers.Where(m => m.GroupId == groupId));

        foreach (var userId in (userIds ?? []).Distinct())
        {
            context.SettingsGroupMembers.Add(new SettingsGroupMember
            {
                GroupId = groupId,
                UserId = userId
            });
        }

        context.SaveChanges();
    }

    /// <summary>
    /// Gets the groups a user belongs to.
    /// </summary>
    /// <param name="userId">The Jellyfin user id.</param>
    /// <returns>The groups, least specific first.</returns>
    public List<SettingsGroup> GetGroupsForUser(Guid userId)
    {
        using var context = CreateContext();

        var groups = context.SettingsGroupMembers.AsNoTracking()
            .Where(m => m.UserId == userId)
            .Join(
                context.SettingsGroups.AsNoTracking(),
                m => m.GroupId,
                g => g.Id,
                (_, g) => g)
            .ToList();

        return SettingsResolver.InLayerOrder(groups).ToList();
    }

    /// <summary>
    /// Gets the settings targeted at one user.
    /// </summary>
    /// <param name="userId">The Jellyfin user id.</param>
    /// <returns>The override, or <c>null</c> when there is none.</returns>
    public UserSettingsOverride? GetUserSettingsOverride(Guid userId)
    {
        using var context = CreateContext();
        return context.UserSettingsOverrides.AsNoTracking()
            .FirstOrDefault(o => o.UserId == userId);
    }

    /// <summary>
    /// Sets the settings targeted at one user.
    /// </summary>
    /// <param name="userId">The Jellyfin user id.</param>
    /// <param name="settingsJson">A partial set of settings, as JSON.</param>
    public void SaveUserSettingsOverride(Guid userId, string settingsJson)
    {
        using var context = CreateContext();

        var existing = context.UserSettingsOverrides.FirstOrDefault(o => o.UserId == userId);
        if (existing is null)
        {
            context.UserSettingsOverrides.Add(new UserSettingsOverride
            {
                UserId = userId,
                SettingsJson = settingsJson
            });
        }
        else
        {
            existing.SettingsJson = settingsJson;
        }

        context.SaveChanges();
    }

    /// <summary>
    /// Clears the settings targeted at one user.
    /// </summary>
    /// <param name="userId">The Jellyfin user id.</param>
    public void RemoveUserSettingsOverride(Guid userId)
    {
        using var context = CreateContext();

        var existing = context.UserSettingsOverrides.FirstOrDefault(o => o.UserId == userId);
        if (existing is null)
        {
            return;
        }

        context.UserSettingsOverrides.Remove(existing);
        context.SaveChanges();
    }

    /// <summary>
    /// Carries device tokens over from the hand written store, once.
    /// </summary>
    /// <remarks>
    /// Failure is not fatal. A server that cannot read the old file still starts,
    /// keeps working with an empty table, and tries again next time, which is the
    /// only acceptable behaviour for something that runs during plugin activation.
    /// </remarks>
    /// <param name="context">An open context on the new database.</param>
    private void ImportLegacyDeviceTokens(StreamyfinDbContext context)
    {
        if (context.ImportMarkers.Any(m => m.Name == ImportMarker.LegacyDeviceTokens))
        {
            return;
        }

        if (!File.Exists(LegacyDbFilePath))
        {
            MarkImported(context, 0);
            return;
        }

        List<DeviceToken> legacy;
        try
        {
            legacy = LegacyDeviceTokenReader.Read(LegacyDbFilePath);
        }
        catch (Exception ex)
        {
            _logger?.LogWarning(
                ex,
                "Could not read the previous database at {Path}. Device tokens were not imported and the import will be retried on the next start",
                LegacyDbFilePath);
            return;
        }

        try
        {
            var known = context.DeviceTokens.Select(t => t.DeviceId).ToHashSet();
            var fresh = legacy.Where(t => !known.Contains(t.DeviceId)).ToList();

            using var transaction = context.Database.BeginTransaction();
            context.DeviceTokens.AddRange(fresh);
            context.ImportMarkers.Add(new ImportMarker
            {
                Name = ImportMarker.LegacyDeviceTokens,
                ImportedAt = DateTimeOffset.UtcNow,
                RowsImported = fresh.Count
            });
            context.SaveChanges();
            transaction.Commit();

            _logger?.LogInformation(
                "Imported {Count} device token(s) from {Path}. The old file is left in place and is not read again",
                fresh.Count,
                LegacyDbFilePath);
        }
        catch (Exception ex)
        {
            _logger?.LogWarning(
                ex,
                "Could not import device tokens from {Path}. The import will be retried on the next start",
                LegacyDbFilePath);
        }
    }

    private static void MarkImported(StreamyfinDbContext context, int rows)
    {
        context.ImportMarkers.Add(new ImportMarker
        {
            Name = ImportMarker.LegacyDeviceTokens,
            ImportedAt = DateTimeOffset.UtcNow,
            RowsImported = rows
        });
        context.SaveChanges();
    }
}
